### ISSUE TITLE
Morning Session: Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by drakecdv** [kensteph/Portfolio#3]
Very nice code! 😃 It is really clean and organized, so no mandatory changes are required.

[OPTIONAL] Use the shorthand versions of padding and margin to maintain your code clean 😉 that would be all!

**Comment by Ellyboi** [comment]
Nice arrangement of codes, the project was clean

[OPTIONAL], always remember to write 'H1' as 'h1'
